### ISSUE TITLE
Some general feedback

### ISSUE THREAD

**Issue by linaori** [taq/phpr#1]
Hello, I saw your library coming by and I'd like to provide some feedback.

There's a few files which still define a php closing tag:
- [src/Collection.php](https://github.com/taq/phpr/blob/master/src/Collection.php)
- [src/ArrayAccessInterface.php](https://github.com/taq/phpr/blob/master/src/ArrayAccessInterface.php)

I was kind of curious why you named your trait "Interface" as well. Maybe `ArrayAccessTrait` would be a more descriptive name when you see it. Also note that if the classes implementing this trait will have to have `$_array` defined, otherwise php will automatically make it a public property.

I noticed you are using reflection in your Collection, for a lot of people that's a no-go as it has a big impact on performance, especially when xdebug is disabled (which you should do in production environments).

Maybe you would be interested in taking a look at [doctrine/collections](https://github.com/doctrine/collections), this is pretty much a library that does nearly the same.

**Comment by taq** [comment]
Hi, thanks for your message!

The interface name comes from a long time using ... interfaces. :-) Yes, they will need to define `$_array`,  but as I'm kind of sure all the other classes that implements it comes from this same package, I think it will not be a problem. 

I really need reflection to get the parameters number. It won't be necessary if PHP have associative (hashes) and non-associative arrays as different classes, but to make it works with both kind of objects I need to use this way. If you have some suggestion to make it better, you're very welcome. 

Yes, Doctrine/Collections seems to have the same goal, but I kind of want a stand-alone class, out of any framework, but who can be used anywhere you want without being part of a framework or something like that. Is like when I loved the Laravel's Fluent ORM, but IMHO at least when I saw it was to tied to the framework, and I made [TORM](https://github.com/taq/torm) which the kind of features and isolation I wanted.

**Comment by taq** [comment]
Uh ... are we ok? Can I close the issue here?

**Comment by linaori** [comment]
Yeah I can close it, just wanted to provide some general feedback :)

Good luck!

**Comment by taq** [comment]
Thanks! :-)
